version: '3'

services:

  api:
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3333/health || exit 1"]
      interval: 5s
    container_name: mandoubem_api
    build: .
    ports:
      - '3333:3333'
    # command: yarn start
    env_file: .env
    depends_on:
      - postgres
      - redis
      - mongo
    network_mode: host


  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
    image: postgres
    container_name: mandoubem_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mandoubem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    network_mode: host

  redis:
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
    image: redis
    container_name: mandoubem_redis
    ports:
      - "6379:6379"
    network_mode: host

  mongo:
    healthcheck:
        test: ["CMD-SHELL", "mongo", "--eval", "db.adminCommand('ping')"]
        interval: 5s
    image: mongo
    container_name: mandoubem_mongodb
    ports:
      - "27017:27017"
    network_mode: host
